{
  "formatVersion": "1.1",
  "component": {
    "group": "me.clip",
    "module": "placeholderapi",
    "version": "2.11.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "placeholderapi-2.11.6.jar",
          "url": "placeholderapi-2.11.6.jar",
          "size": 933017,
          "sha512": "a95aa273bc83b5390b1aecfb239ea8c845524ea631a3d5448d51ab0f7e4a65815c964fad864989f0c5c5f4906e67381eb823e714f2550a8ca818d407fe11dcbf",
          "sha256": "b20cb09db1cd79f76b9172e5114dfde6f34c558069e3bd7b72b14f718bc5dffd",
          "sha1": "0d9ad7a4c2759a6cc5c824cf56e5d06f12333f88",
          "md5": "123c4e956ebe9daa40ef2d337dec41e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.bstats",
          "module": "bstats-bukkit",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-bukkit",
          "version": {
            "requires": "4.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "placeholderapi-2.11.6.jar",
          "url": "placeholderapi-2.11.6.jar",
          "size": 933017,
          "sha512": "a95aa273bc83b5390b1aecfb239ea8c845524ea631a3d5448d51ab0f7e4a65815c964fad864989f0c5c5f4906e67381eb823e714f2550a8ca818d407fe11dcbf",
          "sha256": "b20cb09db1cd79f76b9172e5114dfde6f34c558069e3bd7b72b14f718bc5dffd",
          "sha1": "0d9ad7a4c2759a6cc5c824cf56e5d06f12333f88",
          "md5": "123c4e956ebe9daa40ef2d337dec41e7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "placeholderapi-2.11.6.jar",
          "url": "placeholderapi-2.11.6.jar",
          "size": 933017,
          "sha512": "a95aa273bc83b5390b1aecfb239ea8c845524ea631a3d5448d51ab0f7e4a65815c964fad864989f0c5c5f4906e67381eb823e714f2550a8ca818d407fe11dcbf",
          "sha256": "b20cb09db1cd79f76b9172e5114dfde6f34c558069e3bd7b72b14f718bc5dffd",
          "sha1": "0d9ad7a4c2759a6cc5c824cf56e5d06f12333f88",
          "md5": "123c4e956ebe9daa40ef2d337dec41e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "placeholderapi-2.11.6-javadoc.jar",
          "url": "placeholderapi-2.11.6-javadoc.jar",
          "size": 325189,
          "sha512": "4fdcfbaeb69a075feffa7cd41bb026c8ac58c8d627d085e9d425c27220823bf84b434d8f8431ef7b41af0c0e73d0799809d6d43ecb3368dedd2f843bdff2203a",
          "sha256": "e7226edd158d4fe845f5ddc0a5f5777957f8d658cc3808bfbaab67fde969d4d5",
          "sha1": "ce4131bb9c512794d32b5e346fc49f3582596e6d",
          "md5": "604bb76170067daa5a2ad8d3689853fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "placeholderapi-2.11.6-sources.jar",
          "url": "placeholderapi-2.11.6-sources.jar",
          "size": 82364,
          "sha512": "168d7fb038a6f46927fcae96d96eef4bd0979f7ef5d3266c992f35b5364b16d4a48eafd6b7f597a7f7192cad1f8bd2970dbe5748a0b7c789676a70cad5183a56",
          "sha256": "c5aab5d0613c755e018e94ee43e3c6b8c9a64f1bf240e2bdd1716bac53d4db66",
          "sha1": "b42a4ec35b8e983f03c7cffedff7fa374df9879a",
          "md5": "346052efaf265a7e3c3ea4e49a6b7c5d"
        }
      ]
    }
  ]
}
